# Generated by Django 5.1.4 on 2024-12-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
